apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: streamx-web-route
spec:
  http:
    - name: streamx-web-route
      match:
        hosts:
          - lumax.streamx.com
        paths:
          - /homepage.html
          - /cart.html
          - /my-orders.html
          - /sitemap.xml
          - /assets/*
          - /web-resources/*
          - /fragments/*
          - /_fragments/*
          - /products/*
          - /categories/*
          - /content/dam/*
      priority: 20
      backends:
        - serviceName: sx-del-blueprint-web
          servicePort: 8084
      plugins:
      - name: cors
        enable: true
        config:
          allow_origins: "*"  # Change this to specific origins if needed
          allow_methods: "*"   # Allow all HTTP methods
          allow_headers: "*"   # Allow all headers
          expose_headers: "*"  # Expose all headers
          max_age: 3600
      plugins:
        - name: gzip
          enable: true
          config:
            buffers:
              number: 8
            types: "*"